name: Required PR Checks

on:
  pull_request:
    branches:
      - main
    types: [reopened, ready_for_review, unlocked, synchronize]

jobs:
  conventional_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Validates the pull request
        uses: Namchee/conventional-pr@v0.9.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          # todo: experiment and set limit
          maximum_file_change: 20
          verified_commits: true
          close: false
