name: Release

on:
  push:
    branches:
      - main

jobs:
  release_packages:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Install Dependencies
        run: npm ci --no-audit

      - name: Creating .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            @hitz-group:registry=https://npm.pkg.github.com
            //npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1.2.0
        with:
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Send a Slack notification if a publish happens
        if: steps.changesets.outputs.published == 'true'
        run: echo notify
        # You can do something when a publish happens.
        # run: my-slack-bot send-notification --message "A new version of ${GITHUB_REPOSITORY} was published!"
